import { query } from "./db";
import { seed } from "../seed";

/**
 * 建表 DDL 与 database/init.sql 保持一致；应用启动时幂等执行，
 * 因此即使数据库未经 docker-entrypoint 初始化也能自举。
 * id 使用 GENERATED BY DEFAULT AS IDENTITY：允许种子显式插入固定 id，运行时走 DEFAULT。
 */
const SCHEMA_STATEMENTS: string[] = [
  `CREATE TABLE IF NOT EXISTS measuring_device (
     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     device_code TEXT NOT NULL UNIQUE,
     name TEXT,
     device_type TEXT,
     accuracy_level TEXT,
     owner_dept TEXT,
     calibration_cycle_days INTEGER NOT NULL DEFAULT 365,
     status TEXT NOT NULL DEFAULT 'VALID',
     lifecycle_status TEXT NOT NULL DEFAULT 'ACTIVE',
     exempt_reason TEXT,
     exempt_until TIMESTAMPTZ
   )`,
  `CREATE TABLE IF NOT EXISTS calibration_plan (
     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     device_id BIGINT NOT NULL,
     planned_date TIMESTAMPTZ,
     plan_type TEXT,
     priority TEXT,
     status TEXT,
     assigned_vendor_id BIGINT,
     created_by TEXT
   )`,
  `CREATE TABLE IF NOT EXISTS calibration_certificate (
     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     device_id BIGINT NOT NULL,
     plan_id BIGINT,
     certificate_no TEXT,
     result_status TEXT,
     valid_until TEXT,
     file_path TEXT,
     issued_by TEXT
   )`,
  `CREATE TABLE IF NOT EXISTS calibration_vendor (
     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     vendor_name TEXT,
     qualification_no TEXT,
     contact_phone TEXT,
     service_scope TEXT,
     vendor_status TEXT
   )`,
  `CREATE TABLE IF NOT EXISTS overdue_alert (
     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     device_id BIGINT NOT NULL,
     plan_id BIGINT,
     alert_level TEXT,
     alert_reason TEXT,
     handled_by TEXT,
     handled_at TIMESTAMPTZ,
     status TEXT
   )`,
  `CREATE TABLE IF NOT EXISTS audit_log (
     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     actor TEXT,
     action TEXT,
     target_type TEXT,
     target_id TEXT,
     created_at TIMESTAMPTZ NOT NULL DEFAULT now()
   )`,
  `CREATE TABLE IF NOT EXISTS device_lifecycle_record (
     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     device_id BIGINT NOT NULL,
     action TEXT NOT NULL,
     from_status TEXT NOT NULL,
     to_status TEXT NOT NULL,
     reason TEXT,
     exempt_until TIMESTAMPTZ,
     operated_by TEXT,
     created_at TIMESTAMPTZ NOT NULL
   )`,
  `CREATE INDEX IF NOT EXISTS idx_lifecycle_record_device
     ON device_lifecycle_record (device_id, created_at DESC, id DESC)`,
  `CREATE INDEX IF NOT EXISTS idx_calibration_plan_device
     ON calibration_plan (device_id)`,
  `CREATE TABLE IF NOT EXISTS idempotency_record (
     scope TEXT NOT NULL,
     idempotency_key TEXT NOT NULL,
     status_code INTEGER NOT NULL,
     response JSONB NOT NULL,
     -- 租约归属：owner_token 标识当前持有者；leased_at 为最近一次续租时间，
     -- 持有者执行期间持续心跳；失联（无心跳且超过 TTL）后他人可安全接管。
     owner_token TEXT,
     leased_at TIMESTAMPTZ,
     completed_at TIMESTAMPTZ,
     created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
     -- 幂等键按调用范围隔离：同一 key 在不同写接口（不同 scope）互不串用，
     -- 同一接口同一 key 仍只执行一次。
     PRIMARY KEY (scope, idempotency_key)
   )`,
  // 一次性在线迁移 A：把旧版（idempotency_key 单列主键）表升级为 (scope, idempotency_key) 复合主键。
  `DO $$
     BEGIN
       IF EXISTS (
         SELECT 1 FROM pg_indexes
         WHERE tablename = 'idempotency_record'
           AND indexdef LIKE '%(idempotency_key)%'
           AND indexdef NOT LIKE '%scope%'
       ) THEN
         UPDATE idempotency_record SET scope = 'legacy' WHERE scope IS NULL OR scope = '';
         ALTER TABLE idempotency_record DROP CONSTRAINT idempotency_record_pkey;
         ALTER TABLE idempotency_record ALTER COLUMN scope SET NOT NULL;
         ALTER TABLE idempotency_record ADD PRIMARY KEY (scope, idempotency_key);
       END IF;
     EXCEPTION WHEN undefined_table THEN
       NULL;
     END;
   $$`,
  // 一次性在线迁移 B：为已存在的复合主键表补齐租约列（崩溃接管所需）。
  // 历史未完成占位（status_code=0 且 owner 为空）直接清空，等价于启动即回收。
  `DO $$
     BEGIN
       IF EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'idempotency_record')
          AND NOT EXISTS (SELECT 1 FROM information_schema.columns
                          WHERE table_name = 'idempotency_record' AND column_name = 'owner_token') THEN
         ALTER TABLE idempotency_record ADD COLUMN owner_token TEXT;
         ALTER TABLE idempotency_record ADD COLUMN leased_at TIMESTAMPTZ;
         ALTER TABLE idempotency_record ADD COLUMN completed_at TIMESTAMPTZ;
         DELETE FROM idempotency_record WHERE status_code = 0;
       END IF;
     EXCEPTION WHEN undefined_table THEN
       NULL;
     END;
   $$`
];

const resetIdentity = (table: string): string =>
  `SELECT setval(
     pg_get_serial_sequence('${table}', 'id'),
     GREATEST(COALESCE((SELECT MAX(id) FROM ${table}), 1), 1),
     (SELECT MAX(id) IS NOT NULL FROM ${table})
   )`;

/**
 * 幂等种子：ON CONFLICT DO NOTHING 保证重启/多实例启动不重复插入，
 * 随后把 identity 序列校正到 max(id)，避免运行时主键冲突。
 */
const seedIfEmpty = async (): Promise<void> => {
  for (const d of seed.measuringDevice) {
    await query(
      `INSERT INTO measuring_device
         (id, device_code, name, device_type, accuracy_level, owner_dept, calibration_cycle_days, status, lifecycle_status, exempt_reason, exempt_until)
       VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11)
       ON CONFLICT (id) DO NOTHING`,
      [
        d.id, d.device_code, d.name, d.device_type, d.accuracy_level, d.owner_dept,
        d.calibration_cycle_days, d.status, d.lifecycle_status, d.exempt_reason, d.exempt_until
      ]
    );
  }
  await query(resetIdentity("measuring_device"));

  for (const p of seed.calibrationPlan) {
    await query(
      `INSERT INTO calibration_plan
         (id, device_id, planned_date, plan_type, priority, status, assigned_vendor_id, created_by)
       VALUES ($1,$2,$3,$4,$5,$6,$7,$8) ON CONFLICT (id) DO NOTHING`,
      [p.id, p.device_id, p.planned_date, p.plan_type, p.priority, p.status, p.assigned_vendor_id, p.created_by]
    );
  }
  await query(resetIdentity("calibration_plan"));

  for (const c of seed.calibrationCertificate) {
    await query(
      `INSERT INTO calibration_certificate
         (id, device_id, plan_id, certificate_no, result_status, valid_until, file_path, issued_by)
       VALUES ($1,$2,$3,$4,$5,$6,$7,$8) ON CONFLICT (id) DO NOTHING`,
      [c.id, c.device_id, c.plan_id, c.certificate_no, c.result_status, c.valid_until, c.file_path, c.issued_by]
    );
  }
  await query(resetIdentity("calibration_certificate"));

  for (const v of seed.calibrationVendor) {
    await query(
      `INSERT INTO calibration_vendor
         (id, vendor_name, qualification_no, contact_phone, service_scope, vendor_status)
       VALUES ($1,$2,$3,$4,$5,$6) ON CONFLICT (id) DO NOTHING`,
      [v.id, v.vendor_name, v.qualification_no, v.contact_phone, v.service_scope, v.vendor_status]
    );
  }
  await query(resetIdentity("calibration_vendor"));

  for (const a of seed.overdueAlert) {
    await query(
      `INSERT INTO overdue_alert
         (id, device_id, plan_id, alert_level, alert_reason, handled_by, handled_at, status)
       VALUES ($1,$2,$3,$4,$5,$6,$7,$8) ON CONFLICT (id) DO NOTHING`,
      [a.id, a.device_id, a.plan_id, a.alert_level, a.alert_reason, a.handled_by, a.handled_at, a.status]
    );
  }
  await query(resetIdentity("overdue_alert"));
};

export const bootstrapDatabase = async (): Promise<void> => {
  for (const statement of SCHEMA_STATEMENTS) {
    await query(statement);
  }
  await seedIfEmpty();
};
