-- 设备计量校准排期 API 初始化脚本
-- id 采用 GENERATED BY DEFAULT AS IDENTITY：允许种子显式插入固定 id，应用运行时走 DEFAULT。
-- 与 backend/src/repositories/schema.ts 的建表语句保持一致（应用启动也会幂等自举）。

CREATE TABLE IF NOT EXISTS measuring_device (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  device_code TEXT NOT NULL UNIQUE,
  name TEXT,
  device_type TEXT,
  accuracy_level TEXT,
  owner_dept TEXT,
  calibration_cycle_days INTEGER NOT NULL DEFAULT 365,
  status TEXT NOT NULL DEFAULT 'VALID',
  -- 生命周期：ACTIVE 在役 / EXEMPT 校准豁免 / SCRAPPED 已报废（终态）
  lifecycle_status TEXT NOT NULL DEFAULT 'ACTIVE',
  exempt_reason TEXT,
  exempt_until TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS calibration_plan (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  device_id BIGINT NOT NULL,
  planned_date TIMESTAMPTZ,
  plan_type TEXT,
  priority TEXT,
  status TEXT,
  assigned_vendor_id BIGINT,
  created_by TEXT
);
CREATE INDEX IF NOT EXISTS idx_calibration_plan_device ON calibration_plan (device_id);

CREATE TABLE IF NOT EXISTS calibration_certificate (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  device_id BIGINT NOT NULL,
  plan_id BIGINT,
  certificate_no TEXT,
  result_status TEXT,
  valid_until TEXT,
  file_path TEXT,
  issued_by TEXT
);

CREATE TABLE IF NOT EXISTS calibration_vendor (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  vendor_name TEXT,
  qualification_no TEXT,
  contact_phone TEXT,
  service_scope TEXT,
  vendor_status TEXT
);

CREATE TABLE IF NOT EXISTS overdue_alert (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  device_id BIGINT NOT NULL,
  plan_id BIGINT,
  alert_level TEXT,
  alert_reason TEXT,
  handled_by TEXT,
  handled_at TIMESTAMPTZ,
  status TEXT
);

CREATE TABLE IF NOT EXISTS audit_log (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  actor TEXT,
  action TEXT,
  target_type TEXT,
  target_id TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- 设备生命周期变更记录：仅追加，不改写计划与证书历史。
-- action: EXEMPT 豁免 / EXPIRE_RESTORE 到期自动恢复 / SCRAP 报废
CREATE TABLE IF NOT EXISTS device_lifecycle_record (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  device_id BIGINT NOT NULL,
  action TEXT NOT NULL,
  from_status TEXT NOT NULL,
  to_status TEXT NOT NULL,
  reason TEXT,
  exempt_until TIMESTAMPTZ,
  operated_by TEXT,
  created_at TIMESTAMPTZ NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_lifecycle_record_device
  ON device_lifecycle_record (device_id, created_at DESC, id DESC);

-- 写接口幂等：按调用范围隔离。同一 (scope, Idempotency-Key) 重放首次结果，
-- 重复提交不产生第二条记录；不同写接口（不同 scope）即使 key 相同也互不串用。
-- scope 形如 POST:/api/measuring-device/:id/exempt。
-- owner_token/leased_at 为崩溃接管租约：持有者失联（行锁释放且租约过期）后可被安全接管，
-- 业务写入与结果登记在持有者同一事务提交，保证不执行两次、首次结果可回读。
CREATE TABLE IF NOT EXISTS idempotency_record (
  scope TEXT NOT NULL,
  idempotency_key TEXT NOT NULL,
  status_code INTEGER NOT NULL,
  response JSONB NOT NULL,
  owner_token TEXT,
  leased_at TIMESTAMPTZ,
  completed_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  PRIMARY KEY (scope, idempotency_key)
);
