export const ERROR_CODES = {
  AUTH_REQUIRED: "AUTH_REQUIRED",
  RBAC_DENIED: "RBAC_DENIED",
  VALIDATION_FAILED: "VALIDATION_FAILED",
  RATE_LIMITED: "RATE_LIMITED",
  DEVICE_NOT_FOUND: "DEVICE_NOT_FOUND",
  DEVICE_ALREADY_SCRAPPED: "DEVICE_ALREADY_SCRAPPED",
  DEVICE_ALREADY_EXEMPT: "DEVICE_ALREADY_EXEMPT",
  DEVICE_SCRAP_PLAN_CONFLICT: "DEVICE_SCRAP_PLAN_CONFLICT",
  PLAN_DEVICE_SCRAPPED: "PLAN_DEVICE_SCRAPPED",
  PLAN_DEVICE_EXEMPT: "PLAN_DEVICE_EXEMPT",
  DEVICE_CODE_DUPLICATED: "DEVICE_CODE_DUPLICATED",
  IDEMPOTENCY_REPLAY_PENDING: "IDEMPOTENCY_REPLAY_PENDING",
  PERSISTENCE_FAILED: "PERSISTENCE_FAILED",
  DATABASE_NOT_READY: "DATABASE_NOT_READY"
} as const;
